name: smartproject
description: "A Money Management System with Daily Limits."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.7.7+1
  fl_chart: ^0.66.0
  
  # State Management & Local Storage
  provider: ^6.1.2
  shared_preferences: ^2.3.5
  
  # Networking & API
  http: ^1.2.0
  dio: ^5.4.1
  google_generative_ai: ^0.4.7
  
  # Files, PDF & Images
  file_picker: ^8.0.0
  image_picker: ^1.0.7
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.2
  
  # Utilities
  url_launcher: ^6.3.1
  intl: ^0.19.0
  syncfusion_flutter_pdfviewer: ^32.1.22
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

# Launcher Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png