name: smartproject
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  http: ^1.2.0
  google_generative_ai: ^0.4.7
  flutter_markdown: ^0.7.7+1
  pdf: ^3.11.3
  printing: ^5.14.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.5
  fl_chart: ^0.66.0
  file_picker: ^8.0.0
  image_picker: ^1.0.7
  
  # --- ADDED FOR PDF VIEWING AND DOWNLOADING ---
  flutter_pdfview: ^1.3.2      # The engine to display the PDF
  path_provider: ^2.1.2        # To find the phone's internal storage
  dio: ^5.4.1                  # High-performance downloader for large files

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/notes_database.json