name: Smart-tutor Android CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@v3

      - name: â˜• Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: ğŸ¦ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: ğŸ“¦ Install Dependencies
        run: flutter pub get

      - name: ğŸ› ï¸ Build Android APK
        # This compiles your code into the installable .apk file
        run: flutter build apk --release

      - name: ğŸ“¤ Upload APK Artifact
        # This saves the file on GitHub so you can download it to your phone
        uses: actions/upload-artifact@v4
        with:
          name: smart-tutor-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          - name: ğŸ› ï¸ Build Android APK
        run: flutter build apk --release

      - name: ğŸšš Upload APK to Website Folder
        uses: appleboy/scp-action@master
        with:
          host: "109.199.120.38"
          username: "root"
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "build/app/outputs/flutter-apk/app-release.apk"
          target: "/var/www/smart-tutor"
          strip_components: 4 # This puts the file directly in /var/www/smart-tutor/